FROM nginx:alpine

COPY index.html case.html deposit.html user.html /usr/share/nginx/html/
COPY images/   /usr/share/nginx/html/images/
COPY styles/   /usr/share/nginx/html/styles/
COPY scripts/  /usr/share/nginx/html/scripts/
COPY casev2/   /usr/share/nginx/html/casev2/

EXPOSE 80
