# Generated by Django 5.2 on 2025-05-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='caseitemchance',
            name='drop_chance',
        ),
        migrations.DeleteModel(
            name='TopUp',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
