# Generated by Django 5.2 on 2025-05-01 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_remove_withdrawal_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='caseitemchance',
            options={'verbose_name': 'Предмет в кейсе', 'verbose_name_plural': 'Предметы в кейсе'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'verbose_name': 'Полученный предмет', 'verbose_name_plural': 'Полученные предметы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='withdrawable',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='status',
        ),
        migrations.AlterField(
            model_name='case',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.FileField(upload_to='case-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='caseitemchance',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gamestore.case', verbose_name='Кейс'),
        ),
        migrations.AlterField(
            model_name='caseitemchance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL аватара'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Steam ID'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='item-image/', verbose_name='Изображение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='gamestore.item')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
    ]
