# Generated by Django 5.2 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_alter_case_options_alter_caseitemchance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
