# Generated by Django 5.2 on 2025-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
