# Generated by Django 5.2 on 2025-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0006_iteminstance_for_sale_iteminstance_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
