# Generated by Django 5.2 on 2025-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0007_iteminstance_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'в продаже')], max_length=52, null=True),
        ),
    ]
