# Generated by Django 5.2 on 2025-08-14 12:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Сумма')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('succeeded', 'Успешно'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
